<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OFNnoQHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oFNnoQH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oFNnoQH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'employe' => ['privates', '.errored..service_locator.oFNnoQH.App\\Entity\\Employe', NULL, 'Cannot autowire service ".service_locator.oFNnoQH": it references class "App\\Entity\\Employe" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'employe' => 'App\\Entity\\Employe',
            'entityManager' => '?',
        ]);
    }
}
