<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1yXxVY1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1yXxVY1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1yXxVY1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projetRepository' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'projetRepository' => 'App\\Repository\\ProjetRepository',
            'security' => '?',
        ]);
    }
}
