<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IPzJNuwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iPzJNuw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iPzJNuw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'notification' => ['privates', '.errored..service_locator.iPzJNuw.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.iPzJNuw": it references class "App\\Entity\\Notification" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'notification' => 'App\\Entity\\Notification',
        ]);
    }
}
