<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7PH019EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7PH019E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7PH019E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'etat' => ['privates', '.errored..service_locator.7PH019E.App\\Entity\\Etat', NULL, 'Cannot autowire service ".service_locator.7PH019E": it references class "App\\Entity\\Etat" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'etat' => 'App\\Entity\\Etat',
        ]);
    }
}
