<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetanceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9LDLbRe.App\Entity\Competance' shared service.
     *
     * @return \App\Entity\Competance
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9LDLbRe": it references class "App\\Entity\\Competance" but no such service exists.');
    }
}
