<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDomaine2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wEXE_cx.App\Entity\Domaine' shared service.
     *
     * @return \App\Entity\Domaine
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wEXE_cx": it references class "App\\Entity\\Domaine" but no such service exists.');
    }
}
