<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GaEeKCb.App\Entity\Equipe' shared service.
     *
     * @return \App\Entity\Equipe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.GaEeKCb": it references class "App\\Entity\\Equipe" but no such service exists.');
    }
}
