<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmployeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oFNnoQH.App\Entity\Employe' shared service.
     *
     * @return \App\Entity\Employe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oFNnoQH": it references class "App\\Entity\\Employe" but no such service exists.');
    }
}
