<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFonction2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Y3X3d_D.App\Entity\Fonction' shared service.
     *
     * @return \App\Entity\Fonction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Y3X3d_D": it references class "App\\Entity\\Fonction" but no such service exists.');
    }
}
