<?php

namespace ContainerQNCJxWh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iPzJNuw.App\Entity\Notification' shared service.
     *
     * @return \App\Entity\Notification
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iPzJNuw": it references class "App\\Entity\\Notification" but no such service exists.');
    }
}
