<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipe extends \App\Entity\Equipe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'nom_equipe', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'chef', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'taches', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'membre'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'nom_equipe', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'chef', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'taches', '' . "\0" . 'App\\Entity\\Equipe' . "\0" . 'membre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Equipe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEquipe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEquipe', []);

        return parent::getNomEquipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEquipe(string $nom_equipe): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEquipe', [$nom_equipe]);

        return parent::setNomEquipe($nom_equipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(int $nombre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getChef(): ?\App\Entity\Employe
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChef', []);

        return parent::getChef();
    }

    /**
     * {@inheritDoc}
     */
    public function setChef(?\App\Entity\Employe $chef): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChef', [$chef]);

        return parent::setChef($chef);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaches(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaches', []);

        return parent::getTaches();
    }

    /**
     * {@inheritDoc}
     */
    public function addTach(\App\Entity\Tache $tach): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTach', [$tach]);

        return parent::addTach($tach);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTach(\App\Entity\Tache $tach): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTach', [$tach]);

        return parent::removeTach($tach);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembre(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembre', []);

        return parent::getMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMembre(?array $membre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembre', [$membre]);

        return parent::setMembre($membre);
    }

}
