<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ressource extends \App\Entity\Ressource implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'nom_ressource', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'qty_ressource', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'cout_ressource', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'taches'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'nom_ressource', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'qty_ressource', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'cout_ressource', '' . "\0" . 'App\\Entity\\Ressource' . "\0" . 'taches'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ressource $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomRessource(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomRessource', []);

        return parent::getNomRessource();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomRessource(string $nom_ressource): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomRessource', [$nom_ressource]);

        return parent::setNomRessource($nom_ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtyRessource(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtyRessource', []);

        return parent::getQtyRessource();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtyRessource(int $qty_ressource): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtyRessource', [$qty_ressource]);

        return parent::setQtyRessource($qty_ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoutRessource(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoutRessource', []);

        return parent::getCoutRessource();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoutRessource(int $cout_ressource): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoutRessource', [$cout_ressource]);

        return parent::setCoutRessource($cout_ressource);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaches(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaches', []);

        return parent::getTaches();
    }

    /**
     * {@inheritDoc}
     */
    public function addTach(\App\Entity\Tache $tach): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTach', [$tach]);

        return parent::addTach($tach);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTach(\App\Entity\Tache $tach): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTach', [$tach]);

        return parent::removeTach($tach);
    }

}
