<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OB26OpHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oB26OpH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oB26OpH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'priorite' => ['privates', '.errored..service_locator.oB26OpH.App\\Entity\\Priorite', NULL, 'Cannot autowire service ".service_locator.oB26OpH": it references class "App\\Entity\\Priorite" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'priorite' => 'App\\Entity\\Priorite',
        ]);
    }
}
