<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D0B0RJlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d0B0RJl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d0B0RJl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competance' => ['privates', '.errored..service_locator.d0B0RJl.App\\Entity\\Competance', NULL, 'Cannot autowire service ".service_locator.d0B0RJl": it references class "App\\Entity\\Competance" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'competance' => 'App\\Entity\\Competance',
            'entityManager' => '?',
        ]);
    }
}
