<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4HNHIcLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4HNHIcL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4HNHIcL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
