<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LPGiacUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lPGiacU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lPGiacU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'ressource' => ['privates', '.errored..service_locator.lPGiacU.App\\Entity\\Ressource', NULL, 'Cannot autowire service ".service_locator.lPGiacU": it references class "App\\Entity\\Ressource" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'ressource' => 'App\\Entity\\Ressource',
        ]);
    }
}
