<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y3X3dDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y3X3d_D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y3X3d_D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fonction' => ['privates', '.errored..service_locator.Y3X3d_D.App\\Entity\\Fonction', NULL, 'Cannot autowire service ".service_locator.Y3X3d_D": it references class "App\\Entity\\Fonction" but no such service exists.'],
        ], [
            'fonction' => 'App\\Entity\\Fonction',
        ]);
    }
}
