<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GaEeKCbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GaEeKCb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GaEeKCb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'equipe' => ['privates', '.errored..service_locator.GaEeKCb.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.GaEeKCb": it references class "App\\Entity\\Equipe" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'equipe' => 'App\\Entity\\Equipe',
        ]);
    }
}
