<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHhMHZQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iHhMHZQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHhMHZQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'domaine' => ['privates', '.errored..service_locator.iHhMHZQ.App\\Entity\\Domaine', NULL, 'Cannot autowire service ".service_locator.iHhMHZQ": it references class "App\\Entity\\Domaine" but no such service exists.'],
        ], [
            'domaine' => 'App\\Entity\\Domaine',
        ]);
    }
}
