<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7R6lnheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7R6lnhe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7R6lnhe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'equipe' => ['privates', 'App\\Repository\\EquipeRepository', 'getEquipeRepositoryService', true],
            'notificationRepo' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
            'projet' => ['privates', 'App\\Repository\\ProjetRepository', 'getProjetRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'tache' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'equipe' => 'App\\Repository\\EquipeRepository',
            'notificationRepo' => 'App\\Repository\\NotificationRepository',
            'projet' => 'App\\Repository\\ProjetRepository',
            'security' => '?',
            'tache' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
