<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9LDLbReService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9LDLbRe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9LDLbRe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competance' => ['privates', '.errored..service_locator.9LDLbRe.App\\Entity\\Competance', NULL, 'Cannot autowire service ".service_locator.9LDLbRe": it references class "App\\Entity\\Competance" but no such service exists.'],
        ], [
            'competance' => 'App\\Entity\\Competance',
        ]);
    }
}
