<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriorite2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oB26OpH.App\Entity\Priorite' shared service.
     *
     * @return \App\Entity\Priorite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oB26OpH": it references class "App\\Entity\\Priorite" but no such service exists.');
    }
}
