<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRessource2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lPGiacU.App\Entity\Ressource' shared service.
     *
     * @return \App\Entity\Ressource
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lPGiacU": it references class "App\\Entity\\Ressource" but no such service exists.');
    }
}
