<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRole2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O7MMxHX.App\Entity\Role' shared service.
     *
     * @return \App\Entity\Role
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O7MMxHX": it references class "App\\Entity\\Role" but no such service exists.');
    }
}
