<?php

namespace Container8DQZO9V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTacheService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2lBK97_.App\Entity\Tache' shared service.
     *
     * @return \App\Entity\Tache
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2lBK97_": it references class "App\\Entity\\Tache" but no such service exists.');
    }
}
