<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container95Qqk9K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container95Qqk9K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container95Qqk9K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container95Qqk9K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container95Qqk9K\App_KernelDevDebugContainer([
    'container.build_hash' => '95Qqk9K',
    'container.build_id' => '93c556de',
    'container.build_time' => 1724739737,
], __DIR__.\DIRECTORY_SEPARATOR.'Container95Qqk9K');
