<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdCklWz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdCklWz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdCklWz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdCklWz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXdCklWz\App_KernelDevDebugContainer([
    'container.build_hash' => 'XdCklWz',
    'container.build_id' => '80b80220',
    'container.build_time' => 1724909367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdCklWz');
