<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQzumCJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQzumCJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQzumCJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQzumCJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQzumCJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQzumCJ',
    'container.build_id' => 'afc156c5',
    'container.build_time' => 1725031608,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQzumCJ');
